![ecommerce_analytics-1224x532](ecommerce_analytics-1224x532.jpg)

As a Data Engineer at an electronics e-commerce company, Voltmart, you have been requested by a peer Machine Learning team to clean the data containing the information about orders made last year. They are planning to further use this cleaned data to build a demand forecasting model. To achieve this, they have shared their requirements regarding the desired output table format.

An analyst shared a parquet file called `"orders_data.parquet"` for you to clean and preprocess. 

You can see the dataset schema below along with the **cleaning requirements**:

## `orders_data.parquet`

| column | data type | description | cleaning requirements | 
|--------|-----------|-------------|-----------------------|
| `order_date` | `timestamp` | Date and time when the order was made | _Modify: Remove orders placed between 12am and 5am (inclusive); convert from timestamp to date_ |
| `time_of_day` | `string` | Period of the day when the order was made | _New column containing (lower bound inclusive, upper bound exclusive): "morning" for orders placed 5-12am, "afternoon" for orders placed 12-6pm, and "evening" for 6-12pm_ |
| `order_id` | `long` | Order ID | _N/A_ |
| `product` | `string` | Name of a product ordered | _Remove rows containing "TV" as the company has stopped selling this product; ensure all values are lowercase_ |
| `product_ean` | `double` | Product ID | _N/A_ |
| `category` | `string` | Broader category of a product | _Ensure all values are lowercase_ |
| `purchase_address` | `string` | Address line where the order was made ("House Street, City, State Zipcode") | _N/A_ |
| `purchase_state` | `string` | US State of the purchase address | _New column containing: the State that the purchase was ordered from_ |
| `quantity_ordered` | `long` | Number of product units ordered | _N/A_ |
| `price_each` | `double` | Price of a product unit | _N/A_ |
| `cost_price` | `double` | Cost of production per product unit | _N/A_ |
| `turnover` | `double` | Total amount paid for a product (quantity x price) | _N/A_ |
| `margin` | `double` | Profit made by selling a product (turnover - cost) | _N/A_ |

<br>

In [50]:
from pyspark.sql import (
    SparkSession,
    types,
    functions as F,
)

spark = (
    SparkSession
    .builder
    .appName('cleaning_orders_dataset_with_pyspark')
    .getOrCreate()
)

In [51]:
orders_data = spark.read.parquet('orders_data.parquet')
orders_data.toPandas().head()

           order_date  order_id  ... turnover    margin
0 2023-01-22 21:25:00    141234  ...   700.00  469.0000
1 2023-01-28 14:15:00    141235  ...    14.95    7.4750
2 2023-01-17 13:33:00    141236  ...    23.98   11.9900
3 2023-01-05 20:33:00    141237  ...   149.99   52.4965
4 2023-01-25 11:59:00    141238  ...    11.99    5.9950

[5 rows x 11 columns]

In [52]:
orders_data.count()

185950

Data Cleaning - Order date and time of day

In [53]:
orders_data = (
    orders_data
    .withColumn(
        'time_of_day',
        # When/otherwise (similar to case/when/else) statements extracting hour from timestamp
        F.when((F.hour('order_date') >= 0) & (F.hour('order_date') <= 5), 'night')
         .when((F.hour('order_date') >= 6) & (F.hour('order_date') <= 11), 'morning')
         .when((F.hour('order_date') >= 12) & (F.hour('order_date') <= 17), 'afternoon')
         .when((F.hour('order_date') >= 18) & (F.hour('order_date') <= 23), 'evening')
         .otherwise(None)
    )
    # Filter by time of day
    .filter(
        F.col('time_of_day') != 'night'
    )
    # Cast order_date to date as it is originally a timestamp
    .withColumn(
        'order_date',
        F.col('order_date').cast(types.DateType())
    )
)

Data Cleaning - Product and category lowercase and filtering

In [54]:
orders_data = (
    orders_data
    # Make product and category columns lowercase
    .withColumn(
        'product',
        F.lower('product')
    )
    .withColumn(
        'category',
        F.lower('category')
    )
    # Remove rows where product column contains "tv" (as you have already made it lowercase)
    .filter(
        ~F.col('product').contains('tv')
    )
)

Data transformation - Obtaining the state

In [55]:
orders_data = (
    orders_data
    # First you split the purchase address by space (" ")
    .withColumn(
        'address_split',
        F.split('purchase_address', ' ')
    )
)

In [56]:
orders_data.select('address_split').show(20, False)

+-----------------------------------------------+
|address_split                                  |
+-----------------------------------------------+
|[944, Walnut, St,, Boston,, MA, 02215]         |
|[185, Maple, St,, Portland,, OR, 97035]        |
|[538, Adams, St,, San, Francisco,, CA, 94016]  |
|[738, 10th, St,, Los, Angeles,, CA, 90001]     |
|[387, 10th, St,, Austin,, TX, 73301]           |
|[775, Willow, St,, San, Francisco,, CA, 94016] |
|[979, Park, St,, Los, Angeles,, CA, 90001]     |
|[181, 6th, St,, San, Francisco,, CA, 94016]    |
|[867, Willow, St,, Los, Angeles,, CA, 90001]   |
|[657, Johnson, St,, San, Francisco,, CA, 94016]|
|[492, Walnut, St,, San, Francisco,, CA, 94016] |
|[322, 6th, St,, San, Francisco,, CA, 94016]    |
|[618, 7th, St,, Los, Angeles,, CA, 90001]      |
|[512, Wilson, St,, San, Francisco,, CA, 94016] |
|[440, Cedar, St,, Portland,, OR, 97035]        |
|[471, Center, St,, Los, Angeles,, CA, 90001]   |
|[414, Walnut, St,, Boston,, MA, 02215]         |
|[220, 9th, St,, Los, Angeles,, CA, 90001]      |
|[238, Sunset, St,, Seattle,, WA, 98101]        |
|[764, 11th, St,, Los, Angeles,, CA, 90001]     |
+-----------------------------------------------+
only showing top 20 rows

In [57]:
# Based on the rows above, the state abbreviation is always at the 2nd last position
orders_data = (
    orders_data
    .withColumn(
        'purchase_state',
        F.col('address_split').getItem(F.size('address_split') - 2)
    )
    # Dropping address_split columns as it is a temporary technical column
    .drop('address_split')
)

Checking number of unique states

In [58]:
# Use distinct and count to calculate the number of unique values
n_states = (
    orders_data
    .select('purchase_state')
    .distinct()
    .count()
)
n_states

8

Checking the cleaned data

In [59]:
orders_data.show(20,False)

+----------+--------+--------------------------+-----------------+------------+---------------------------------------+----------------+----------+------------------+--------+--------+-----------+--------------+
|order_date|order_id|product                   |product_id       |category    |purchase_address                       |quantity_ordered|price_each|cost_price        |turnover|margin  |time_of_day|purchase_state|
+----------+--------+--------------------------+-----------------+------------+---------------------------------------+----------------+----------+------------------+--------+--------+-----------+--------------+
|2023-01-22|141234  |iphone                    |5.638008983335E12|vêtements   |944 Walnut St, Boston, MA 02215        |1               |700.0     |231.0             |700.0   |469.0   |evening    |MA            |
|2023-01-28|141235  |lightning charging cable  |5.563319511488E12|alimentation|185 Maple St, Portland, OR 97035       |1               |14.95     |7.475             |14.95   |7.475   |afternoon  |OR            |
|2023-01-17|141236  |wired headphones          |2.11397339522E12 |vêtements   |538 Adams St, San Francisco, CA 94016  |2               |11.99     |5.995             |23.98   |11.99   |afternoon  |CA            |
|2023-01-05|141237  |27in fhd monitor          |3.069156759167E12|sports      |738 10th St, Los Angeles, CA 90001     |1               |149.99    |97.4935           |149.99  |52.4965 |evening    |CA            |
|2023-01-25|141238  |wired headphones          |9.692680938163E12|électronique|387 10th St, Austin, TX 73301          |1               |11.99     |5.995             |11.99   |5.995   |morning    |TX            |
|2023-01-29|141239  |aaa batteries (4-pack)    |2.953868554188E12|alimentation|775 Willow St, San Francisco, CA 94016 |1               |2.99      |1.495             |2.99    |1.495   |evening    |CA            |
|2023-01-26|141240  |27in 4k gaming monitor    |5.173670800988E12|vêtements   |979 Park St, Los Angeles, CA 90001     |1               |389.99    |128.69670000000002|389.99  |261.2933|afternoon  |CA            |
|2023-01-05|141241  |usb-c charging cable      |8.051736777568E12|vêtements   |181 6th St, San Francisco, CA 94016    |1               |11.95     |5.975             |11.95   |5.975   |afternoon  |CA            |
|2023-01-01|141242  |bose soundsport headphones|1.508418177978E12|électronique|867 Willow St, Los Angeles, CA 90001   |1               |99.99     |49.995            |99.99   |49.995  |morning    |CA            |
|2023-01-22|141243  |apple airpods headphones  |1.38634421159E12 |électronique|657 Johnson St, San Francisco, CA 94016|1               |150.0     |97.5              |150.0   |52.5    |evening    |CA            |
|2023-01-07|141244  |apple airpods headphones  |4.332898830865E12|vêtements   |492 Walnut St, San Francisco, CA 94016 |1               |150.0     |97.5              |150.0   |52.5    |morning    |CA            |
|2023-01-31|141245  |macbook pro laptop        |1.169379570345E12|vêtements   |322 6th St, San Francisco, CA 94016    |1               |1700.0    |561.0             |1700.0  |1139.0  |morning    |CA            |
|2023-01-09|141246  |aaa batteries (4-pack)    |4.436184749366E12|vêtements   |618 7th St, Los Angeles, CA 90001      |3               |2.99      |1.495             |8.97    |4.485   |evening    |CA            |
|2023-01-25|141247  |27in fhd monitor          |7.313825995563E12|vêtements   |512 Wilson St, San Francisco, CA 94016 |1               |149.99    |97.4935           |149.99  |52.4965 |evening    |CA            |
|2023-01-05|141249  |27in fhd monitor          |9.643428300795E12|alimentation|440 Cedar St, Portland, OR 97035       |1               |149.99    |97.4935           |149.99  |52.4965 |afternoon  |OR            |
|2023-01-10|141250  |vareebadd phone           |6.721780072847E12|alimentation|471 Center St, Los Angeles, CA 90001   |1               |400.0     |132.0             |400.0   |268.0   |morning    |CA            |
|2023-01-24|141251  |apple airpods headphones  |2.700099961823E12|alimentation|414 Walnut St, Boston, MA 02215        |1               |150.0     |97.5              |150.0   |52.5    |morning    |MA            |
|2023-01-30|141252  |usb-c charging cable      |3.692435232121E12|sports      |220 9th St, Los Angeles, CA 90001      |1               |11.95     |5.975             |11.95   |5.975   |morning    |CA            |
|2023-01-08|141254  |aaa batteries (4-pack)    |8.219536039183E12|électronique|238 Sunset St, Seattle, WA 98101       |1               |2.99      |1.495             |2.99    |1.495   |morning    |WA            |
|2023-01-09|141255  |usb-c charging cable      |7.739134543383E12|alimentation|764 11th St, Los Angeles, CA 90001     |1               |11.95     |5.975             |11.95   |5.975   |evening    |CA            |
+----------+--------+--------------------------+-----------------+------------+---------------------------------------+----------------+----------+------------------+--------+--------+-----------+--------------+
only showing top 20 rows

In [60]:
orders_data.count()

170921

Exporting the data

In [61]:
orders_data.write.parquet(
    'orders_data_clean.parquet',
    mode='overwrite',
)